# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- release
- oldrel


os:
  - linux
  - osx

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -LO http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C / ; fi

after_success:
  - Rscript -e 'covr::codecov()'
