// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lm_rcpp
List lm_rcpp(arma::mat X, arma::vec y, CharacterVector X_names);
RcppExport SEXP _econr_lm_rcpp(SEXP XSEXP, SEXP ySEXP, SEXP X_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type X_names(X_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_rcpp(X, y, X_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_econr_lm_rcpp", (DL_FUNC) &_econr_lm_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_econr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
