# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_rcpp <- function(X, y, X_names) {
    .Call(`_econr_lm_rcpp`, X, y, X_names)
}

